spring:
  datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    url: jdbc:postgresql://localhost:5432/moodi
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: PostgreSQL
  flyway:
    locations: classpath:db/migration/common,classpath:db/migration/psql

integration:
  moodle:
    baseUrl: https://moodle.helsinki.fi
  oodi.url: https://esbmt1.it.helsinki.fi/secure/doo-oodi/v1/productiondb
  iam.url: https://esbmt1.it.helsinki.fi
  sisu:
    baseUrl: https://gw.api.helsinki.fi/secure/sisu
    apiKey: ${apiGatewayApiKey}

# Also known as the synced role
mapper.moodle.role.moodi: 11

mapper:
  moodle:
    categoriesByOrgId:
      hy-org-46074265: 2 # Bio- ja ympäristötieteellinen
      hy-org-75261982: 31 # Helsingin yliopiston kirjasto
      hy-org-1000000957: 54 # Svenska social- och kommunalhögskolan
      hy-org-48645785: 75 # Avoin yliopisto
