spring:
  datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    url: jdbc:postgresql://localhost:5432/moodi
    username: ${datasource.username}
    password: ${datasource.password}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: PostgreSQL

integration:
  moodle:
    baseUrl: https://moodi-2-moodle.student.helsinki.fi/moodlecurrent
    url: https://moodi-2-moodle.student.helsinki.fi/moodlecurrent/webservice/rest/server.php
  oodi.url: https://oprek4.it.helsinki.fi:30040
  esb.url: https://esbmt1.it.helsinki.fi