spring:
  datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    url: jdbc:postgresql://localhost:5432/moodi
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: PostgreSQL
  flyway:
    locations: classpath:db/migration/common,classpath:db/migration/psql

integration:
  moodle:
    baseUrl: https://moodi-2-moodle.student.helsinki.fi/moodlecurrent
    url: https://moodi-2-moodle.student.helsinki.fi/moodlecurrent/webservice/rest/server.php
  oodi.url: https://esbmt1.it.helsinki.fi/secure/doo-oodi/v1/productiondb
  esb.url: https://esbmt1.it.helsinki.fi