spring:
  datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    url: jdbc:postgresql://localhost:5432/moodi
    username: ${datasource.username}
    password: ${datasource.password}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: PostgreSQL

integration:
  moodle:
    baseUrl: https://moodle.helsinki.fi
    url: https://moodle.helsinki.fi/webservice/rest/server.php
  oodi.url: https://esbmt1.it.helsinki.fi/doo-oodi/v1/productiondb
  esb.url: https://esbmt1.it.helsinki.fi