spring:
  datasource:
    dataSourceClassName: org.h2.jdbcx.JdbcDataSource
    url: jdbc:h2:mem:moodi;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: PostgreSQL
  flyway:
    locations: classpath:db/migration/common

auth.client.user: password
auth.enabled: true

dev.mode.enabled: true

synchronize.FULL.enabled: false
synchronize.INCREMENTAL.enabled: false

logging:
  retain-logs: PT30M
  file-logging-path: /tmp/log/moodi-import-sync-log