server.port: 8084

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
      show-details: always # The health endpoint is not publicly reachable, so we can give out details to facilitate troubleshooting.

httpClient:
  readTimeout: 15000
  connectTimeout: 3000
  maxTotal: 500
  defaultMaxPerRoute: 500

oodi.enrollmentApprovedStatusCodes: 2, 3, 7, 8

mapper.moodle.defaultCategory: 2

#
# Map application roles to Moodle's internal role IDs.
#
mapper.moodle.role.teacher: 3
mapper.moodle.role.student: 5
# Also known as the synced role
mapper.moodle.role.moodi: 10

synchronize.FULL.enabled: true
synchronize.INCREMENTAL.enabled: false

logging:
  retain-logs: P30D
  file-logging-path: /var/log/moodi-import-sync-log

spring.jpa.hibernate.ddl-auto: none
spring.jpa.generate-ddl: false

auth.enabled: true

dev.mode.enabled: false

syncTresholds:
  REMOVE_ROLES:
    preventAll: 5
  SUSPEND_ENROLLMENT:
    preventAll: 5

mailNotification:
  from: moodi-app
  lockedMessageSubject: Synchronization locked
