spring:
  datasource:
    dataSourceClassName: org.h2.jdbcx.JdbcDataSource
    url: jdbc:h2:mem:moodi;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: PostgreSQL
  flyway:
    locations: classpath:db/migration/common, classpath:db/migration/h2

auth.client.testclient: xxx123
auth.enabled: true

integration:
  moodle:
    baseUrl: https://moodi-2-moodle-20.student.helsinki.fi/moodlecurrent
    wstoken: xxxx1234
  sisu:
    baseUrl: http://localhost:9876
    apiKey: test-apikey

synchronize.FULL.enabled: true
synchronize.INCREMENTAL.enabled: false

logging:
  retain-logs: PT30M
  file-logging-path: /tmp/log/moodi-import-sync-log
  level:
    root: info

    org:
      mockserver: error
      springframework:
          transaction: debug
          orm:
              jpa: debug
    fi:
      helsinki:
        moodi:
          test:
            templates: info
mailNotification.to: nonexistingemailaddress@helsinki.fi
