spring:
  datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    url: jdbc:postgresql://localhost:5432/moodi
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: PostgreSQL
  flyway:
    locations: classpath:db/migration/common,classpath:db/migration/psql

integration:
  moodle:
    baseUrl: https://moodle.helsinki.fi
  oodi.url: https://esbmt1.it.helsinki.fi/secure/doo-oodi/v1/productiondb
  iam.url: https://esbmt1.it.helsinki.fi

mapper.moodle.defaultCategory: 73
# Also known as the synced role
mapper.moodle.role.moodi: 11
