spring:
  datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    url: jdbc:postgresql://localhost:5432/moodi
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: PostgreSQL
  flyway:
    locations: classpath:db/migration/common,classpath:db/migration/psql

integration:
  moodle:
    baseUrl: https://moodi-2-moodle-20.student.helsinki.fi/moodlecurrent
  oodi.url: https://esbmt1.it.helsinki.fi/secure/doo-oodi/v1/productiondb
  iam.url: https://esbmt1.it.helsinki.fi
  sisu:
    baseUrl: http://localhost:9876
    apiKey: qa-apikey
