server.port: 8084

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true

httpClient:
  readTimeout: 15000
  connectTimeout: 3000
  maxTotal: 500
  defaultMaxPerRoute: 500

oodi.enrollmentApprovedStatusCodes: 3, 7, 8

mapper.moodle.defaultCategory: 73

#
# Map application roles to Moodle's internal role IDs.
#
mapper.moodle.role.teacher: 3
mapper.moodle.role.student: 5
mapper.moodle.role.moodi: 11

synchronize.FULL.enabled: true
synchronize.INCREMENTAL.enabled: false

logging:
  retain-logs: P30D
  file-logging-path: /var/log/moodi-import-sync-log

spring.jpa.hibernate.ddl-auto: none
spring.jpa.generate-ddl: false

auth.enabled: true

dev.mode.enabled: false

syncTresholds:
  REMOVE_ROLES:
    preventAll: 5

mailNotification:
  from: moodi-app
  lockedMessageSubject: Synchronization locked
