server.port: 8084

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
      show-details: always # The health endpoint is not publicly reachable, so we can give out details to facilitate troubleshooting.

httpClient:
  # Determines the timeout in milliseconds until a connection is established.
  connectTimeout: 9000
  # Defines the socket timeout (SO_TIMEOUT) in milliseconds,
  # which is the timeout for waiting for data  or, put differently,
  # a maximum period inactivity between two consecutive data packets).
  socketTimeout: 15000

oodi.enrollmentApprovedStatusCodes: 2, 3, 7, 8

mapper.moodle.defaultCategory: 17
# Some Moodle categories are overridden for the prod environment.
mapper:
  moodle:
    categoriesByOrgId:
      hy-org-46074265: 22 # Bio- ja ympäristötieteellinen
      hy-org-1001813360: 3 # Eläinlääketieteellinen
      hy-org-41547372: 4 # Farmasian tiedekunta
      hy-org-1000000842: 5 # Humanistinen tiedekunta
      hy-org-1000000939: 6 # Kasvatustieteellinen tiedekunta
      hy-org-1000000836: 7 # Lääketieteellinen tiedekunta
      hy-org-1000000941: 8 # Maatalous-metsätieteellinen tiedekunta
      hy-org-1000000911: 9 # Matemaattis-luonnontieteellinen tiedekunta
      hy-org-1000000821: 10 # Oikeustieteellinen tiedekunta
      hy-org-1000000580: 11 # Teologinen tiedekunta
      hy-org-1000000940: 12 # Valtiotieteellinen tiedekunta
      hy-org-75261977: 13 # Erillislaitokset
      hy-org-1000003401: 15 # Kielikeskus
      hy-org-1001813375: 20 # Henkilöstökoulutus
      hy-org-122782928: 21 # Tutkimusyksiköt ja verkostot
      hy-org-75261982: 22 # Helsingin yliopiston kirjasto
      hy-org-1000000957: 19 # Svenska social- och kommunalhögskolan
      hy-org-48645785: 24 # Avoin yliopisto
      hy-org-98574580: 25 # Tutkijakoulut ja tohtoriohjelmat

#
# Map application roles to Moodle's internal role IDs.
#
mapper.moodle.role.teacher: 3
mapper.moodle.role.student: 5
# Also known as the synced role
mapper.moodle.role.moodi: 10

synchronize.FULL.enabled: true
synchronize.INCREMENTAL.enabled: false

logging:
  retain-logs: P30D
  file-logging-path: /var/log/moodi-import-sync-log

spring.jpa.hibernate.ddl-auto: none
spring.jpa.generate-ddl: false

auth.enabled: true

dev.mode.enabled: false

syncTresholds:
  REMOVE_ROLES:
    preventAll: 5
  SUSPEND_ENROLLMENT:
    preventAll: 5

mailNotification:
  from: moodi-app
  lockedMessageSubject: Synchronization locked
