spring:
  datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    url: jdbc:postgresql://localhost:5432/moodi
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: PostgreSQL
  flyway:
      locations: classpath:db/migration/common
      table: schema_version
      ignore-missing-migrations: true

integration:
  moodle:
    baseUrl: https://moodi-2-moodle-20.student.helsinki.fi/moodlecurrent
  sisu:
    baseUrl: https://gw-api-test.it.helsinki.fi/secure/sisu
    apiKey: ${apiGatewayApiKey}

dev.mode.enabled: true

synchronize.FULL.enabled: false
